---
description: "Más información sobre: ' exit Try ' solo puede aparecer dentro de una instrucción ' Try '"
title: "'Exit Try' solo puede aparecer dentro de una instrucción 'Try'"
ms.date: 07/20/2015
f1_keywords:
- vbc30393
- bc30393
helpviewer_keywords:
- BC30393
ms.assetid: b8651df3-a32f-478c-a6d8-aa0ef584155f
ms.openlocfilehash: dc99c591b984ef6dc6bbda3f3875b42e78d0c56f
ms.sourcegitcommit: 10e719780594efc781b15295e499c66f316068b8
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 02/14/2021
ms.locfileid: "100465215"
---
# <a name="exit-try-can-only-appear-inside-a-try-statement"></a>'Exit Try' solo puede aparecer dentro de una instrucción 'Try'

`Exit Try` solo puede aparecer dentro de una instrucción de bloque `Try` . O bien tiene una instrucción `Exit Try` redundante o su instrucción `Exit Try` aparece fuera de los límites del bloque `Try` correspondiente.  
  
 **Identificador de error:** BC30393  
  
## <a name="to-correct-this-error"></a>Para corregir este error  
  
1. Busque y quite la instrucción `Exit Try` innecesaria.  
  
2. Mueva la `Exit Try` instrucción al lugar adecuado del código.  
  
## <a name="see-also"></a>Vea también

- [Try...Catch...Finally (instrucción)](../language-reference/statements/try-catch-finally-statement.md)
