---
description: Advertencia del compilador (nivel 1) CS4014
title: Advertencia del compilador (nivel 1) CS4014
ms.date: 08/18/2020
f1_keywords:
- CS4014
helpviewer_keywords:
- CS4014
ms.assetid: b9e7c029-eaa9-48d7-8b3c-9823772c9acb
ms.openlocfilehash: 6118ac43672dca053bee57fdf16ac68ad6d61aee
ms.sourcegitcommit: 05d0087dfca85aac9ca2960f86c5efd218bf833f
ms.translationtype: HT
ms.contentlocale: es-ES
ms.lasthandoff: 03/27/2021
ms.locfileid: "105637551"
---
# <a name="compiler-warning-level-1-cs4014"></a>Advertencia del compilador (nivel 1) CS4014

Dado que no se esperaba esta llamada, la ejecución del método actual continuará antes de que se complete la llamada. Valore la posibilidad de aplicar el operador `await` al resultado de la llamada.

El método actual llama a un método asincrónico que devuelve <xref:System.Threading.Tasks.Task> o <xref:System.Threading.Tasks.Task%601>, y no aplica el operador [await](../operators/await.md) al resultado. La llamada al método asincrónico inicia una tarea asincrónica. Pero, dado que no se aplica un operador `await` , el programa continúa sin esperar a que se complete la tarea. En la mayoría de los casos, este comportamiento no es el esperado. Normalmente otros aspectos del método de llamada dependen de los resultados de la llamada o, como mínimo, se espera que el método llamado se complete antes de volver del método que contiene la llamada.

Otro problema igual de importante es lo que sucede con las excepciones que se producen en el método asincrónico llamado. Una excepción que aparece en un método que devuelve un valor <xref:System.Threading.Tasks.Task> o <xref:System.Threading.Tasks.Task%601> se almacena en la tarea devuelta. Si no espera la tarea o comprueba explícitamente las excepciones, se perderá la excepción. Si espera la tarea, su excepción se volverá a producir.

El procedimiento recomendado es esperar siempre la llamada.

Considere la posibilidad de suprimir la advertencia solamente si está seguro de que no quiere esperar a que se complete la llamada asincrónica y que el método llamado no producirá excepciones. En ese caso, puede suprimir la advertencia asignando el resultado de la tarea de la llamada a una variable.

En el ejemplo siguiente se muestra cómo provocar la advertencia, cómo suprimirla y cómo esperar la llamada.

```csharp
static async Task CallingMethodAsync(int millisecondsDelay)
{
    Console.WriteLine("  Entering calling method.");

    // Call #1.
    // Call an async method. Because you don't await it, its completion
    // isn't coordinated with the current method, CallingMethodAsync.
    // The following line causes warning CS4014.
    CalledMethodAsync(millisecondsDelay);

    // Call #2.
    // To suppress the warning without awaiting, you can assign the
    // returned task to a variable. The assignment doesn't change how
    // the program runs. However, recommended practice is always to
    // await a call to an async method.

    // Replace Call #1 with the following line.
    // Task delayTask = CalledMethodAsync(millisecondsDelay);

    // Call #3
    // To contrast with an awaited call, replace the unawaited call
    // (Call #1 or Call #2) with the following awaited call. Best
    // practice is to await the call.

    // await CalledMethodAsync(millisecondsDelay);

    Console.WriteLine("  Returning from calling method.");
}

static async Task CalledMethodAsync(int millisecondsDelay)
{
    Console.WriteLine("    Entering called method, starting and awaiting Task.Delay.");

    await Task.Delay(millisecondsDelay);

    Console.WriteLine("    Task.Delay is finished--returning from called method.");
}
```

En el ejemplo, si elige Call #1 o Call #2, el método asincrónico no esperado `CalledMethodAsync` termina después de que se completen su llamador `CallingMethodAsync` y el llamador del llamador. La última línea de la salida siguiente muestra cuándo finaliza el método llamado. La entrada y la salida del controlador de eventos que llama a `CallingMethodAsync` en el ejemplo completo se marcan en la salida.

```console
Entering the Click event handler.
  Entering calling method.
    Entering called method, starting and awaiting Task.Delay.
  Returning from calling method.
Exiting the Click event handler.
    Task.Delay is finished--returning from called method.
```

También puede suprimir las advertencias del compilador mediante las directivas [#pragma warning](../preprocessor-directives.md#pragma-warning).

## <a name="example"></a>Ejemplo

La siguiente aplicación de consola contiene los métodos del ejemplo anterior. Los siguientes pasos sirven para configurar la aplicación.

1. Cree una aplicación de consola y denomínela `AsyncWarning`.
1. En el editor de Visual Studio Code, elija el archivo *Program.cs*.
1. Reemplace el código de *Program.cs* por el código siguiente.

    ```csharp
    using System;
    using System.Threading.Tasks;

    namespace AsyncWarning
    {
        class Program
        {
            static async Task Main()
            {
                Console.WriteLine("Entering Main() application entry point.");

                int millisecondsDelay = 2000;
                await CallingMethodAsync(millisecondsDelay);

                Console.WriteLine("Exiting Main() application entry point.");

                await Task.Delay(millisecondsDelay + 500);
            }

            static async Task CallingMethodAsync(int millisecondsDelay)
            {
                Console.WriteLine("  Entering calling method.");

                // Call #1.
                // Call an async method. Because you don't await it, its completion
                // isn't coordinated with the current method, CallingMethodAsync.
                // The following line causes warning CS4014.
                // CalledMethodAsync(millisecondsDelay);

                // Call #2.
                // To suppress the warning without awaiting, you can assign the
                // returned task to a variable. The assignment doesn't change how
                // the program runs. However, recommended practice is always to
                // await a call to an async method.

                // Replace Call #1 with the following line.
                //Task delayTask = CalledMethodAsync(millisecondsDelay);

                // Call #3
                // To contrast with an awaited call, replace the unawaited call
                // (Call #1 or Call #2) with the following awaited call. Best
                // practice is to await the call.

                // await CalledMethodAsync(millisecondsDelay);

                Console.WriteLine("  Returning from calling method.");
            }

            static async Task CalledMethodAsync(int millisecondsDelay)
            {
                Console.WriteLine("    Entering called method, starting and awaiting Task.Delay.");

                await Task.Delay(millisecondsDelay);

                Console.WriteLine("    Task.Delay is finished--returning from called method.");
            }
        }

        // Output with Call #1 or Call #2. (Wait for the last line to appear.)

        // Entering Main() application entry point.
        //   Entering calling method.
        //     Entering called method, starting and awaiting Task.Delay.
        //   Returning from calling method.
        // Exiting Main() application entry point.
        //     Task.Delay is finished--returning from called method.

        // Output with Call #3, which awaits the call to CalledMethodAsync.

        // Entering Main() application entry point.
        //   Entering calling method.
        //     Entering called method, starting and awaiting Task.Delay.
        //     Task.Delay is finished--returning from called method.
        //   Returning from calling method.
        // Exiting Main() application entry point.
    }
    ```

1. Para ejecutar el programa, seleccione la tecla <kbd>F5</kbd>.

La salida esperada aparece al final del código.

## <a name="see-also"></a>Vea también

- [await](../operators/await.md)
- [Programación asincrónica con async y await](../../programming-guide/concepts/async/index.md)
